Drop unused `types` crate
We can add it when needed and currently, we get a clippy warning because
of it:

error: identical args used in this `assert_eq!` macro call
 --> types/src/lib.rs:5:20
  |
5 |         assert_eq!(2 + 2, 4);
  |                    ^^^^^^^^
  |
  = note: `#[deny(clippy::eq_op)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#eq_op